// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {event} from '../models';
import {experiment} from '../models';
import {main} from '../models';
import {metrics} from '../models';

export function AppendEvent(arg1:string,arg2:string,arg3:string):Promise<event.Event>;

export function CreateExperiment(arg1:string,arg2:string):Promise<experiment.Experiment>;

export function DeleteExperiment(arg1:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetDBStatus():Promise<string>;

export function GetExperiment(arg1:string):Promise<experiment.Experiment>;

export function GetLatestMetrics(arg1:string):Promise<Array<metrics.Metric>>;

export function GetLayout():Promise<main.LayoutState>;

export function Greet(arg1:string):Promise<string>;

export function ListExperiments():Promise<Array<experiment.Experiment>>;

export function QueryMetrics(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<metrics.Metric>>;

export function QueryRewardSignals(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<metrics.RewardSignal>>;

export function RecordMetrics(arg1:string,arg2:Array<metrics.Metric>):Promise<void>;

export function RecordRewardSignals(arg1:string,arg2:Array<metrics.RewardSignal>):Promise<void>;

export function ReplayEvents(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<event.Event>>;

export function SaveLayout(arg1:main.LayoutState):Promise<void>;

export function UpdateExperimentStatus(arg1:string,arg2:string):Promise<void>;
