// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendEvent'](arg1, arg2, arg3);
}

export function CreateAnnotation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAnnotation'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateExperiment(arg1, arg2) {
  return window['go']['main']['App']['CreateExperiment'](arg1, arg2);
}

export function DeleteAnnotation(arg1, arg2) {
  return window['go']['main']['App']['DeleteAnnotation'](arg1, arg2);
}

export function DeleteExperiment(arg1) {
  return window['go']['main']['App']['DeleteExperiment'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDBStatus() {
  return window['go']['main']['App']['GetDBStatus']();
}

export function GetExperiment(arg1) {
  return window['go']['main']['App']['GetExperiment'](arg1);
}

export function GetLatestMetrics(arg1) {
  return window['go']['main']['App']['GetLatestMetrics'](arg1);
}

export function GetLayout() {
  return window['go']['main']['App']['GetLayout']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListExperiments() {
  return window['go']['main']['App']['ListExperiments']();
}

export function QueryAnnotations(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryAnnotations'](arg1, arg2, arg3, arg4);
}

export function QueryMetrics(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryMetrics'](arg1, arg2, arg3, arg4);
}

export function QueryRewardSignals(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryRewardSignals'](arg1, arg2, arg3, arg4);
}

export function RecordMetrics(arg1, arg2) {
  return window['go']['main']['App']['RecordMetrics'](arg1, arg2);
}

export function RecordRewardSignals(arg1, arg2) {
  return window['go']['main']['App']['RecordRewardSignals'](arg1, arg2);
}

export function ReplayEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplayEvents'](arg1, arg2, arg3, arg4);
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function UpdateExperimentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateExperimentStatus'](arg1, arg2);
}
