// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {event} from '../models';
import {annotation} from '../models';
import {experiment} from '../models';
import {project} from '../models';
import {alerts} from '../models';
import {main} from '../models';
import {metrics} from '../models';

export function AppendEvent(arg1:string,arg2:string,arg3:string):Promise<event.Event>;

export function ClaimExperimentToCurrentProject(arg1:string):Promise<void>;

export function ClaimExperimentToProject(arg1:string,arg2:string):Promise<void>;

export function CloseProject():Promise<void>;

export function CreateAnnotation(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<annotation.Annotation>;

export function CreateExperiment(arg1:string,arg2:string):Promise<experiment.Experiment>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<project.Project>;

export function DeleteAnnotation(arg1:string,arg2:number):Promise<void>;

export function DeleteExperiment(arg1:string):Promise<void>;

export function GetAlerts(arg1:string):Promise<Array<alerts.Alert>>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCurrentProject():Promise<project.Project>;

export function GetCurrentProjectStatus():Promise<main.CurrentProjectStatus>;

export function GetDBStatus():Promise<string>;

export function GetDefaultProjectsDir():Promise<string>;

export function GetDetections(arg1:string):Promise<Array<alerts.DetectionResult>>;

export function GetExperiment(arg1:string):Promise<experiment.Experiment>;

export function GetLatestMetrics(arg1:string):Promise<Array<metrics.Metric>>;

export function GetLayout():Promise<main.LayoutState>;

export function GetProjectConfig(arg1:string):Promise<project.FluxConfig>;

export function Greet(arg1:string):Promise<string>;

export function IsFluxProject(arg1:string):Promise<boolean>;

export function ListExperiments():Promise<Array<experiment.Experiment>>;

export function ListRecentProjects():Promise<Array<project.RecentProject>>;

export function ListUnscopedExperiments():Promise<Array<experiment.Experiment>>;

export function OpenFolderAsProject(arg1:string,arg2:string,arg3:boolean):Promise<project.Project>;

export function OpenFolderDialog():Promise<string>;

export function OpenProject(arg1:string):Promise<project.Project>;

export function QueryAnnotations(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<annotation.Annotation>>;

export function QueryMetrics(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<metrics.Metric>>;

export function QueryRewardSignals(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<metrics.RewardSignal>>;

export function RecordMetrics(arg1:string,arg2:Array<metrics.Metric>):Promise<void>;

export function RecordRewardSignals(arg1:string,arg2:Array<metrics.RewardSignal>):Promise<void>;

export function RemoveRecentProject(arg1:string):Promise<void>;

export function ReplayEvents(arg1:string,arg2:number,arg3:number,arg4:string):Promise<Array<event.Event>>;

export function SaveLayout(arg1:main.LayoutState):Promise<void>;

export function ToggleMaximize():Promise<void>;

export function UpdateExperimentStatus(arg1:string,arg2:string):Promise<void>;
