// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppendEvent(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendEvent'](arg1, arg2, arg3);
}

export function CreateAnnotation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAnnotation'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateExperiment(arg1, arg2) {
  return window['go']['main']['App']['CreateExperiment'](arg1, arg2);
}

export function DeleteAnnotation(arg1, arg2) {
  return window['go']['main']['App']['DeleteAnnotation'](arg1, arg2);
}

export function DeleteExperiment(arg1) {
  return window['go']['main']['App']['DeleteExperiment'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetDBStatus() {
  return window['go']['main']['App']['GetDBStatus']();
}

export function GetExperiment(arg1) {
  return window['go']['main']['App']['GetExperiment'](arg1);
}

export function GetLatestMetrics(arg1) {
  return window['go']['main']['App']['GetLatestMetrics'](arg1);
}

export function GetLayout() {
  return window['go']['main']['App']['GetLayout']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListExperiments() {
  return window['go']['main']['App']['ListExperiments']();
}

export function QueryAnnotations(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryAnnotations'](arg1, arg2, arg3, arg4);
}

export function QueryMetrics(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryMetrics'](arg1, arg2, arg3, arg4);
}

export function QueryRewardSignals(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['QueryRewardSignals'](arg1, arg2, arg3, arg4);
}

export function RecordMetrics(arg1, arg2) {
  return window['go']['main']['App']['RecordMetrics'](arg1, arg2);
}

export function RecordRewardSignals(arg1, arg2) {
  return window['go']['main']['App']['RecordRewardSignals'](arg1, arg2);
}

export function ReplayEvents(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ReplayEvents'](arg1, arg2, arg3, arg4);
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function ClaimExperimentToCurrentProject(arg1) {
  return window['go']['main']['App']['ClaimExperimentToCurrentProject'](arg1);
}

export function ClaimExperimentToProject(arg1, arg2) {
  return window['go']['main']['App']['ClaimExperimentToProject'](arg1, arg2);
}

export function CloseProject() {
  return window['go']['main']['App']['CloseProject']();
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetCurrentProjectStatus() {
  return window['go']['main']['App']['GetCurrentProjectStatus']();
}

export function GetProjectConfig(arg1) {
  return window['go']['main']['App']['GetProjectConfig'](arg1);
}

export function IsFluxProject(arg1) {
  return window['go']['main']['App']['IsFluxProject'](arg1);
}

export function GetDefaultProjectsDir() {
  return window['go']['main']['App']['GetDefaultProjectsDir']();
}

export function ListRecentProjects() {
  return window['go']['main']['App']['ListRecentProjects']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RemoveRecentProject(arg1) {
  return window['go']['main']['App']['RemoveRecentProject'](arg1);
}

export function ListUnscopedExperiments() {
  return window['go']['main']['App']['ListUnscopedExperiments']();
}

export function OpenFolderAsProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFolderAsProject'](arg1, arg2, arg3);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ToggleMaximize() {
  return window['go']['main']['App']['ToggleMaximize']();
}

export function UpdateExperimentStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateExperimentStatus'](arg1, arg2);
}
